auth/README.md, auth/lib/auth.js, auth/package-lock.json, auth/test/create-access-token.test.js, auth/test/verify-access-token.test.js
=> refactor(auth): remove mongoose model support

packages/amqp/src/lib/client.ts, packages/amqp/src/lib/publisher.ts, packages/amqp/src/lib/subscriber.ts, packages/amqp/src/lib/worker.ts, packages/amqp/test/rpc/rpc.feature, packages/amqp/test/rpc/support/steps.ts
Fix amqp converting large number to buffer when sending message.
- [JIRA Card](https://identifi.atlassian.net/browse/BO-402)
=> feat: stringify and parse message arguments

packages/amqp/src/lib/client.ts, packages/amqp/src/lib/publisher.ts, packages/amqp/src/lib/subscriber.ts, packages/amqp/src/lib/worker.ts, packages/amqp/test/rpc/rpc.feature
Stringify adn parsed worker response
=> feat: stringify and parsed worker response

packages/arque-core/__tests__/event-store/database/mongodb.spec.ts, packages/arque-core/__tests__/helpers.ts, packages/arque-core/src/lib/event-store/database/mongodb.ts
Deeply convert Binary properties in event.body that mongoose itself
does not seem to convert automatically when using Schema.Types.Mixed.
=> feat(arque): convert Binary props to Buffer

packages/amqp/package-lock.json, packages/amqp/package.json, packages/amqp/src/lib/client.ts, packages/amqp/test/rpc/rpc.feature, packages/amqp/test/rpc/support/steps.ts
=> feat: add support for delay message

packages/arque-core/package-lock.json, packages/arque-core/src/lib/projection.ts
Temporary fix to prevent setting this.lastEvent to an older event.id
which causes some issue when starting the projection.
=> fix(projection): prevent setting this.lastEvent to older event.id

packages/ckeditor5-modern/README.md, packages/ckeditor5-modern/package.json
fix common update dependencies
=> fix common update dependencies

packages/ckeditor5/src/components/HOVEditor/HOVEditor.tsx
fix windows undefined hov editor
=> fix windows undefined hov editor

packages/ckeditor5-modern/example/index.tsx, packages/ckeditor5-modern/src/ModernEditor/components/ImageGrid/ImageGrid.tsx
=> added props for images

packages/amqp/src/lib/worker.ts
=> feat(amqp): improve worker logs

packages/ckeditor5/src/components/HOVEditor/HOVEditor.tsx
Added infinite dropdown limit for mentionables
=> Infinite mentionable limit

packages/email-auth/.eslintignore, packages/email-auth/.eslintrc, packages/email-auth/.gitignore, packages/email-auth/__tests__/index.spec.ts, packages/email-auth/__tests__/setup.ts, packages/email-auth/docker-compose.yml, packages/email-auth/global.d.ts, packages/email-auth/jest.config.js, packages/email-auth/logger.ts, packages/email-auth/package-lock.json, packages/email-auth/package.json, packages/email-auth/src/app.ts, packages/email-auth/src/db.ts, packages/email-auth/src/index.ts, packages/email-auth/src/mongoose-adapter.ts, packages/email-auth/src/send-grid-adapter.ts, packages/email-auth/src/server.ts, packages/email-auth/src/types.ts, packages/email-auth/tsconfig.json
Add an `Email Authentication Middleware` along with the following:
=> feat(api): add email authentication middleware

packages/object-id/package-lock.json, packages/object-id/package.json
fix: fix main entrypoint of object-id
=> fix: fix main entrypoint of object-id

packages/repository/package.json, packages/repository/src/repository.ts, packages/repository/src/types.ts
fix: fix ObjectId type mismatch errors
=> fix: fix ObjectId type mismatch errors

packages/email-auth/package-lock.json, packages/email-auth/package.json, packages/email-auth/src/adapters/send-grid-email-adapter.spec.ts, packages/email-auth/src/adapters/send-grid-email-adapter.ts
feat(email-auth): add sendgrid email adapter on email auth
=> feat(email-auth): add sendgrid email adapter on email auth

packages/email-auth/.eslintrc, packages/email-auth/.prettierrc, packages/email-auth/__tests__/app.next.ts, packages/email-auth/__tests__/index.next.spec.ts, packages/email-auth/jest.config.js, packages/email-auth/package-lock.json, packages/email-auth/package.json, packages/email-auth/src/adapters/mongoose-storage-adapter.ts, packages/email-auth/src/email-auth-server.ts, packages/email-auth/src/lib/types.ts, packages/email-auth/tsconfig.json
feat(email-auth): implement generate otp on email auth
=> feat(email-auth): implement generate otp on email auth

packages/repository/src/repository.ts
=> feat: add get model function

packages/repository/src/repository.ts
feat: add TEntity return type for updateOne function
=> feat: add TEntity return type for updateOne function

packages/repository/src/repository.ts
feat: add query options on find function
=> feat: add query options on find function

package-lock.json, package.json, packages/graphql-object-id/README.md, packages/graphql-object-id/package-lock.json, packages/graphql-object-id/package.json, packages/graphql-object-id/src/index.ts, packages/graphql-object-id/tsconfig.json, packages/object-id/package.json
- add `graphql-object-id` package
- fix build setup
=> add `graphql-object-id` package

packages/ui-components/src/components/ThemeProvider.tsx, packages/ui-components/src/index.tsx, packages/ui-components/src/theme/colors.ts, packages/ui-components/src/theme/components/index.ts, packages/ui-components/src/theme/config.ts, packages/ui-components/src/theme/fontSizes.ts, packages/ui-components/src/theme/fonts.ts, packages/ui-components/src/theme/index.ts, packages/ui-components/src/theme/styles.ts, packages/ui-components/src/theme/zIndices.ts, packages/ui-components/src/theme/zindex.ts
- renamed `Provider` to `ThemeProvider` and exported `ThemeProviderProps`
- replaced `ChakraProviderProps` with `ThemeProviderProps`
- refactored `theme` files
- added `Slider` and friends components
=> Calvo jp/jp

packages/ckeditor5/src/components/HOVEditor/HOVEditor.tsx
=> Editor focus

packages/email-auth/__tests__/app.next.ts, packages/email-auth/__tests__/app.ts, packages/email-auth/__tests__/index.next.spec.ts, packages/email-auth/src/adapters/mongoose-storage-adapter.ts, packages/email-auth/src/email-auth-server.ts, packages/email-auth/src/interfaces/storage-adapter.ts, packages/email-auth/src/lib/types.ts, packages/email-auth/tsconfig.json
feat(email-auth): implement validate otp
=> feat(email-auth): implement validate otp

packages/email-auth/src/index.ts
feat: export email auth server to index
=> feat: export email auth server to index

packages/ui-components/src/icons/HovIcon.tsx, packages/ui-components/src/icons/index.tsx, packages/ui-components/src/index.tsx, packages/ui-components/src/layouts/Contact/ContactCard.stories.tsx, packages/ui-components/src/layouts/Contact/ContactCard.tsx, packages/ui-components/src/layouts/Contact/ContactForm.stories.tsx, packages/ui-components/src/layouts/Contact/ContactForm.tsx, packages/ui-components/src/layouts/Contact/ContactPage.stories.tsx, packages/ui-components/src/layouts/Contact/ContactPage.tsx, packages/ui-components/src/layouts/Contact/ContractForm.stories.tsx, packages/ui-components/src/theme/components/text.ts
chore(fe): added contact page and export all contact form related component
=> chore(fe): added contact page and export all contact form related component

packages/email-auth/package-lock.json, packages/email-auth/package.json, packages/email-auth/tsconfig.json
fix(email-auth): fix email auth type definition
=> fix(email-auth): fix email auth type definition

packages/repository/src/repository.ts
feat(repository): add deleteOne function
=> feat(repository): add deleteOne function

packages/analytics/.gitignore, packages/analytics/.npmignore, packages/analytics/package-lock.json, packages/analytics/package.json, packages/analytics/src/index.ts, packages/analytics/tsconfig.json
=> chore(analytics): setup

packages/analytics/.eslintrc, packages/analytics/.prettierrc.yaml, packages/analytics/jest.config.js, packages/analytics/package-lock.json, packages/analytics/package.json, packages/analytics/src/index.ts, packages/analytics/tests/analytics.spec.ts, packages/analytics/tsconfig.json
Add `createAccount()`. This will save user data into Mixpanel.
=> feat(analytics): add createAccount()

packages/ui-components/src/layouts/Contact/Contact.test.tsx, packages/ui-components/src/layouts/Contact/ContactCard.tsx, packages/ui-components/src/layouts/Contact/ContactPage.tsx
chore(ui-components): added contact page test
chore(ui-components): added contact card test
=> chore(ui-components): update contact form test

packages/analytics/.npmignore, packages/analytics/package.json, packages/analytics/tsconfig.json
Able to install the package but unable to import it. No `dist/` on previous build.
=> chore(analytics): update tsconfig.json

package-lock.json, package.json, packages/ui-components/package-lock.json, packages/ui-components/src/hooks/useSupport.tsx, packages/ui-components/src/index.tsx, packages/ui-components/src/layouts/Contact/Contact.test.tsx, packages/ui-components/src/layouts/Contact/ContactCard.tsx, packages/ui-components/src/layouts/Contact/ContactForm.tsx, packages/ui-components/src/layouts/Contact/ContactPage.tsx, packages/ui-components/src/layouts/Contact/validation.ts
chore(ui-components): added hook for notion support integration
=> chore(ui-components): added hook for notion support integration

packages/support/src/support-server.ts
fix: fix default request blocking issue
=> fix: fix default request blocking issue

packages/ui-components/.gitignore, packages/ui-components/README.md, packages/ui-components/src/components/Pagination/Pagination.stories.tsx, packages/ui-components/src/components/Pagination/Pagination.tsx, packages/ui-components/src/layouts/Auth/OTPForm.stories.tsx
chore(ui-components): pagination refactor story usage and update OTP form location
=> chore(ui-components): pagination refactor story usage and update OTP form location

packages/email-auth/src/email-auth-server.ts
add EmailAuthServer#validateJWT on @highoutput/email-auth
=> feat(email-auth): added validateJWT method on email-auth-server

packages/email-auth/src/email-auth-server.ts, packages/email-auth/src/lib/types.ts
fixed (method) validateJWT using wrong return type
=> fix(email-auth): added return type Claims for (method) validateJWT

packages/cli/package-lock.json, packages/cli/package.json
Add package for `@types/ramda`
=> chore: add @types/ramda

packages/billing/__tests__/billing.test.js, packages/billing/__tests__/test-config.json, packages/billing/package-lock.json, packages/billing/package.json, packages/billing/src/lib/billing.js, packages/billing/src/lib/read-config.spec.ts, packages/billing/src/lib/read-config.ts, packages/billing/src/modules/init.ts, packages/billing/src/types/index.ts
Refactor `readConfig`  as a dedicated module and include JSON-schema validation. It includes related tests as well.
=> chore(billing): refactor readConfig

packages/billing/__tests__/init.spec.ts, packages/billing/jest.config.js, packages/billing/package-lock.json, packages/billing/package.json, packages/billing/tsconfig.json
Added test for the `init` module of billing-cli.
=> test(billing): add test for init module of billing-cli

packages/billing/__tests__/fixture.ts, packages/billing/__tests__/get-tiers.spec.ts, packages/billing/package-lock.json, packages/billing/package.json, packages/billing/src/billing-server.ts, packages/billing/src/interfaces/authorization-adapter.ts, packages/billing/src/lib/route-handlers.ts, packages/billing/src/lib/setup.ts
Add GET /tiers endpoint to retrieve the list of pricing tiers. It includes related tests as well.
=> feat(billing): add billing server

packages/billing/__tests__/get-secret.spec.ts, packages/billing/src/billing-server.ts, packages/billing/src/lib/route-handlers.ts
Added GET /secret endpoint to retrieve the client secret needed to setup payments. It includes related tests as well.
=> feat(billing): add GET /secret endpoint

packages/ui-components/src/components/AuthProvider/AuthProvider.stories.mdx
=> chore(ui-components): added auth providers docs

packages/billing/__tests__/get-secret.spec.ts, packages/billing/__tests__/get-tiers.spec.ts, packages/billing/package-lock.json, packages/billing/package.json, packages/billing/src/billing-server.ts, packages/billing/src/lib/route-handlers.ts
Updated `GET /tiers` endpoint to return product tiers from config file.
=> chore(billing): update GET /tiers to use data from json file

packages/ui-components/src/components/ArrayField/ArrayField.stories.tsx, packages/ui-components/src/components/ArrayField/ArrayField.test.tsx, packages/ui-components/src/components/ArrayField/ArrayField.tsx, packages/ui-components/src/components/ArrayField/validation.ts
=> feature(ui-components): Array Field

packages/billing/__tests__/fixture.ts, packages/billing/__tests__/get-secret.spec.ts, packages/billing/__tests__/get-tiers.spec.ts, packages/billing/__tests__/put-subscription.spec.ts, packages/billing/package-lock.json, packages/billing/package.json, packages/billing/src/adapters/mongoose-storage-adapter.ts, packages/billing/src/billing-server.ts, packages/billing/src/interfaces/storage-adapter.ts, packages/billing/src/lib/route-handlers.ts, packages/billing/src/types/index.ts
Added `PUT /subscription` endpoint to update a user's subscription. It includes related tests as well. A `StorageAdapter` is also added to update users db.
=> feat(billing): add PUT /subscription endpoint

packages/billing/__tests__/get-subscription.spec.ts, packages/billing/src/adapters/mongoose-storage-adapter.ts, packages/billing/src/interfaces/storage-adapter.ts, packages/billing/src/lib/route-handlers.ts
Added `GET /subscription endpoint to retrieve a user's subscription. It includes related tests as well.
=> chore(billing): add GET /subscription

packages/billing/__tests__/get-portal.spec.ts, packages/billing/src/billing-server.ts, packages/billing/src/lib/route-handlers.ts
Added `GET /portal` endpoint to redirect client to the customer portal. It includes related tests as well.
=> chore(billing): add GET /portal endpoint

packages/billing/__tests__/get-portal.spec.ts, packages/billing/__tests__/get-secret.spec.ts, packages/billing/__tests__/get-subscription.spec.ts, packages/billing/__tests__/get-tiers.spec.ts, packages/billing/__tests__/init.spec.ts, packages/billing/__tests__/put-subscription.spec.ts, packages/billing/__tests__/test-config.json, packages/billing/src/billing-server.ts, packages/billing/src/interfaces/storage-adapter.ts, packages/billing/src/lib/create-products.spec.ts, packages/billing/src/lib/read-config.ts, packages/billing/src/lib/route-handlers.ts, packages/billing/src/lib/setup-webhook.spec.ts, packages/billing/src/lib/setup-webhook.ts, packages/billing/src/lib/webhook-handler.ts, packages/billing/src/modules/init.ts, packages/billing/src/types/index.ts, packages/billing/tsconfig.build.json
Added endpoint to handle webhook events from Stripe.
=> feat(billing): add webhook endpoint

packages/billing/__tests__/get-portal.spec.ts, packages/billing/__tests__/get-secret.spec.ts, packages/billing/__tests__/get-subscription.spec.ts, packages/billing/__tests__/put-subscription.spec.ts, packages/billing/__tests__/webhook.spec.ts, packages/billing/src/adapters/mongoose-storage-adapter.ts, packages/billing/src/billing-server.ts, packages/billing/src/interfaces/storage-adapter.ts, packages/billing/src/lib/route-handlers.ts, packages/billing/src/lib/webhook-handler.ts, packages/billing/src/types/custom.d.ts, packages/billing/src/types/index.ts, packages/billing/tsconfig.json
Refactored `route-handlers.ts` and `StorageAdapter` interface.
=> chore(billing): refactor route handlers

packages/billing-next/src/adapters/mongoose-stripe-provider-storage.adapter.ts, packages/billing-next/src/interfaces/stripe.provider.ts, packages/billing-next/src/providers/stripe.provider.test.ts, packages/billing-next/src/providers/stripe.provider.ts
Updated `#initializeCustomerPortal` to update a portal configuration that already exists. This includes related tests as well.
=> feat(billing): update existing portal configuration

packages/billing-next/__tests__/get-portal.test.ts, packages/billing-next/src/index.ts, packages/billing-next/src/interfaces/api.provider.ts, packages/billing-next/src/providers/express-api.provider.ts
Added `GET /portal` to redirect a user to the customer portal. This includes related tests as well.
=> feat(billing): redirect to customer portal

packages/billing-next/__tests__/helpers/generate-fake-id.ts, packages/billing-next/__tests__/put-subscription.test.ts, packages/billing-next/src/adapters/mongoose-stripe-provider-storage.adapter.ts, packages/billing-next/src/index.ts, packages/billing-next/src/interfaces/api.provider.ts, packages/billing-next/src/interfaces/stripe.provider.ts, packages/billing-next/src/providers/express-api.provider.test.ts, packages/billing-next/src/providers/express-api.provider.ts
Added `PUT /subscription` to update a user's subscription. This includes integration and unit tests.
=> feat(billing): update user's subscription

packages/cli/.eslintrc, packages/cli/__tests__/database/create.spec.ts, packages/cli/__tests__/database/delete.spec.ts, packages/cli/__tests__/database/inspect.spec.ts, packages/cli/__tests__/database/list.spec.ts, packages/cli/__tests__/deployment/create.spec.ts, packages/cli/__tests__/deployment/deploy.spec.ts, packages/cli/__tests__/deployment/inspect.spec.ts, packages/cli/__tests__/deployment/list.spec.ts, packages/cli/__tests__/deployment/logs.spec.ts, packages/cli/__tests__/deployment/update.spec.ts, packages/cli/__tests__/helpers.next/generate-database.ts, packages/cli/__tests__/helpers.next/generate-deployment.ts, packages/cli/__tests__/helpers.next/generate-user.ts, packages/cli/__tests__/helpers.ts, packages/cli/__tests__/user/list.spec.ts, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/library/client.test.ts, packages/cli/src/modules/deployment/create.ts, packages/cli/src/types/index.ts
feat: add docker file optional parameter on hovcli deployment create command
=> feat: add docker file optional parameter on hovcli deployment create command

packages/billing-next/__tests__/get-secret.test.ts, packages/billing-next/__tests__/get-subscription.test.ts, packages/billing-next/__tests__/get-tiers.spec.ts, packages/billing-next/__tests__/helpers/generate-fake-id.ts, packages/billing-next/__tests__/post-webhook.test.ts, packages/billing-next/__tests__/put-subscription.test.ts, packages/billing-next/src/adapters/mongoose-stripe-provider-storage.adapter.ts, packages/billing-next/src/index.ts, packages/billing-next/src/interfaces/api.provider.ts, packages/billing-next/src/interfaces/stripe.provider.ts, packages/billing-next/src/providers/api.provider.test.ts, packages/billing-next/src/providers/api.provider.ts
Added `POST /webhook` to handle webhook events from Stripe. This includes related tests.
=> feat(billing): handle Stripe webhook events

packages/cli/__tests__/deployment/update.spec.ts, packages/cli/src/modules/deployment/create.ts, packages/cli/src/modules/deployment/update.ts
feat: add dockerfile optional parameter in deployment update command
=> feat: add dockerfile optional parameter in deployment update command

packages/billing-next/__tests__/get-portal.test.ts, packages/billing-next/__tests__/get-secret.test.ts, packages/billing-next/__tests__/get-subscription.test.ts, packages/billing-next/__tests__/get-tiers.spec.ts, packages/billing-next/__tests__/post-webhook.test.ts, packages/billing-next/__tests__/put-subscription.test.ts, packages/billing-next/package-lock.json, packages/billing-next/package.json, packages/billing-next/src/adapters/mongoose-stripe-provider-storage.adapter.ts, packages/billing-next/src/index.ts, packages/billing-next/src/interfaces/api.provider.ts, packages/billing-next/src/interfaces/stripe.provider.ts, packages/billing-next/src/providers/api.provider.test.ts, packages/billing-next/src/providers/api.provider.ts, packages/billing-next/src/providers/config.provider.ts
Applied the following changes:
* set network retries in Stripe config
* refactored the Customer, Subscription, and Response types
* removed `#insertSubscription` from `ApiProvider#putSubscription`
=> chore(billing): refactor ApiProvider

packages/ui-components/src/components/LogoSpinner/LogoSpinner.tsx
replaced deprecated `loop` property with the new property `repeat`
=> replaced deprecated loop property with the new property repeat

packages/cli/__tests__/deployment/inspect.spec.ts, packages/cli/__tests__/helpers.ts, packages/cli/src/library/render-deployment.test.ts, packages/cli/src/library/render-deployment.ts
feat: add Dockerfile property on render deployment
=> feat: add Dockerfile property on render deployment

packages/cli/__tests__/deployment/inspect.spec.ts, packages/cli/__tests__/helpers.ts, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/library/render-deployment.test.ts, packages/cli/src/library/render-deployment.ts, packages/ui-components/src/components/For/For.spec.tsx, packages/ui-components/src/components/For/For.stories.tsx, packages/ui-components/src/components/For/For.tsx, packages/ui-components/src/components/Mount/Mount.spec.tsx, packages/ui-components/src/components/Mount/Mount.stories.tsx, packages/ui-components/src/components/Mount/Mount.tsx, packages/ui-components/src/index.tsx
Added `For` and `Mount` utility components (`SolidJS` inspired)
=> Utility components
